# -*- coding: utf-8 -*-
"""AutoEITipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1safRDBnOKE741MwIhkOaoT5B55W5chkV
"""

import re
import unicodedata
import openpyxl
from copy import copy
from collections import Counter

# ─────────────────────────────────────────────
# 1. TEXT NORMALISATION
# ─────────────────────────────────────────────

def normalise(text):
    """Lowercase, strip accents for comparison, remove punctuation."""
    if not isinstance(text, str):
        return ""
    # Remove transcription artifacts: false starts in [], dashes, filler markers
    text = re.sub(r'\[.*?\]', ' ', text)   # remove bracketed content
    text = re.sub(r'-\w+', ' ', text)       # remove cut-off words (word-)
    text = re.sub(r'\bXXX+\b', ' ', text, flags=re.IGNORECASE)
    text = re.sub(r'[¿¡?!,.:;"\']', ' ', text)
    text = text.lower().strip()
    # Strip accents (for overlap matching — á→a etc.)
    nfd = unicodedata.normalize('NFD', text)
    return ''.join(c for c in nfd if unicodedata.category(c) != 'Mn')


def tokenise(text):
    """Split into word tokens."""
    return [w for w in re.split(r'\s+', normalise(text)) if w]

# ─────────────────────────────────────────────
# 2. SPANISH STOPWORD LIST (function words)
#    Content words = everything NOT in this set
# ─────────────────────────────────────────────

STOPWORDS = {
    'el', 'la', 'los', 'las', 'un', 'una', 'unos', 'unas',
    'de', 'del', 'al', 'a', 'en', 'con', 'por', 'para',
    'que', 'se', 'me', 'te', 'le', 'nos', 'les',
    'y', 'e', 'o', 'u', 'pero', 'sino', 'porque', 'si',
    'es', 'son', 'era', 'eran', 'fue', 'fueron',
    'ha', 'han', 'he', 'has', 'hemos',
    'su', 'sus', 'mi', 'mis', 'tu', 'tus',
    'este', 'esta', 'estos', 'estas', 'ese', 'esa',
    'yo', 'tu', 'el', 'ella', 'nosotros', 'ellos', 'ellas',
    'muy', 'mas', 'tan', 'tanto', 'ya', 'no', 'ni',
    'como', 'cuando', 'donde', 'quien', 'cual', 'cuales',
    'lo', 'le', 'les', 'nos',
    'hay', 'ser', 'estar', 'tener', 'haber',
}


def content_words(text):
    """Return set of content words (non-stopwords) from text."""
    return set(t for t in tokenise(text) if t not in STOPWORDS and len(t) > 1)

# ─────────────────────────────────────────────
# 3. SCORE-0 DETECTION
# ─────────────────────────────────────────────

SILENCE_PATTERNS = re.compile(
    r'^\s*(\[\.{2,}\]|\.{2,}|xxx+|silencio|silence|nothing|\[en ingles?\])\s*$',
    re.IGNORECASE
)

def is_score_zero(raw_transcription):
    """Return True if response should score 0 by rubric."""
    if not isinstance(raw_transcription, str):
        return True
    t = raw_transcription.strip()
    if not t:
        return True
    if SILENCE_PATTERNS.match(t):
        return True
    # English response — all tokens are English (no Spanish chars or common words)
    if re.search(r'\[en ingl', t, re.IGNORECASE):
        return True
    # Only 1 content word total
    cw = content_words(t)
    if len(cw) <= 1:
        # Also check raw tokens — "El ladrón famoso" has 2 content words
        tokens = [w for w in tokenise(t) if len(w) > 1]
        if len(tokens) <= 1:
            return True
    return False

# ─────────────────────────────────────────────
# 4. MEANING-CHANGE & GRAMMAR DETECTORS
# ─────────────────────────────────────────────

# Grammatical structures whose loss signals score degradation
# (relative clause markers, reflexive-indirect constructions)
GRAMMAR_PATTERNS = [
    (r'\bal que\b', 'relative pronoun "al que" dropped to "que"'),
    (r'\bse le\b',  'indirect reflexive "se le" simplified'),
]

def has_grammar_degradation(prompt_norm, learner_norm):
    """
    Detect loss of key grammatical structures that human raters penalise.
    E.g. 'al que' → 'que' (relative pronoun degradation) caps score at 3.
    """
    for (pattern, _) in GRAMMAR_PATTERNS:
        if re.search(pattern, prompt_norm) and not re.search(pattern, learner_norm):
            return True
    return False

# Word pairs that flip meaning — if learner substitutes these, cap at 2
MEANING_OPPOSITES = [
    ('negro', 'blanco'), ('blanco', 'negro'),
    ('baratos', 'caros'), ('caros', 'baratos'),
    ('dificil', 'facil'), ('facil', 'dificil'),
    ('fuman', 'beben'), ('beben', 'fuman'),
    ('murio', 'nacio'), ('triste', 'feliz'), ('feliz', 'triste'),
    ('bajar', 'subir'), ('subir', 'bajar'),
    ('disminuido', 'incrementado'), ('incrementado', 'disminuido'),
    ('calor', 'frio'), ('frio', 'calor'),
    ('gusta', 'odia'), ('odia', 'gusta'),
    ('bien', 'mal'), ('mal', 'bien'),
]

def has_meaning_flip(prompt_norm, learner_norm):
    """Detect if learner substituted an antonym — meaning changed."""
    for (a, b) in MEANING_OPPOSITES:
        if a in prompt_norm and b in learner_norm and a not in learner_norm:
            return True
    return False

def negation_added_or_removed(prompt_norm, learner_norm):
    """Detect negation change (no added/removed)."""
    prompt_has_no = bool(re.search(r'\bno\b', prompt_norm))
    learner_has_no = bool(re.search(r'\bno\b', learner_norm))
    return prompt_has_no != learner_has_no

# ─────────────────────────────────────────────
# 5. CORE SCORING FUNCTION
# ─────────────────────────────────────────────

def score_utterance(stimulus, transcription):
    """
    Apply the meaning-based rubric and return a score 0–4.

    Rubric logic:
      0: Silence / unintelligible / only 1 content word
      1: ≤ 40% content word overlap OR very few tokens
      2: 41–65% overlap OR meaning slightly changed
         (Also: negation flip, antonym substitution, major structural loss)
      3: 66–90% overlap AND meaning preserved
         (Minor grammar changes, synonyms, small omissions OK)
      4: > 90% overlap AND no meaning changes AND no structural loss
         (Near-perfect repetition; false starts, filler do not penalise)
    """
    # ── Score 0 ──────────────────────────────
    if is_score_zero(transcription):
        return 0, "Silence/unintelligible/minimal"

    prompt_norm  = normalise(stimulus)
    learner_norm = normalise(transcription)

    prompt_cw  = content_words(stimulus)
    learner_cw = content_words(transcription)

    if not prompt_cw:
        return 4, "Prompt has no content words"

    # Overlap ratio: what fraction of prompt content words appear in learner?
    overlap     = len(prompt_cw & learner_cw)
    total_union = len(prompt_cw | learner_cw)
    overlap_ratio = overlap / len(prompt_cw)  # recall-style: how much of prompt is covered

    # ── Score 0 edge: only 1 content word in learner ──
    if len(learner_cw) <= 1:
        return 0, f"Only {len(learner_cw)} content word(s) in learner response"

    # ── Meaning-change checks ─────────────────
    meaning_flipped  = has_meaning_flip(prompt_norm, learner_norm)
    negation_changed = negation_added_or_removed(prompt_norm, learner_norm)

    # ── Score 4 ──────────────────────────────
    if overlap_ratio >= 0.90 and not meaning_flipped and not negation_changed:
        return 4, f"Near-perfect ({overlap_ratio:.0%} overlap, no meaning changes)"

    # ── Score 3 ──────────────────────────────
    if overlap_ratio >= 0.66 and not meaning_flipped and not negation_changed:
        return 3, f"Meaning preserved ({overlap_ratio:.0%} overlap)"

    # ── Score 2 ──────────────────────────────
    if overlap_ratio >= 0.40:
        if meaning_flipped:
            return 2, f"Meaning changed - antonym substitution ({overlap_ratio:.0%} overlap)"
        if negation_changed:
            return 2, f"Negation added/removed ({overlap_ratio:.0%} overlap)"
        return 2, f"Partial meaning ({overlap_ratio:.0%} overlap)"

    # ── Score 1 ──────────────────────────────
    if overlap_ratio > 0.15:
        return 1, f"Limited content preserved ({overlap_ratio:.0%} overlap)"

    # ── Score 0 ──────────────────────────────
    return 0, f"Insufficient content ({overlap_ratio:.0%} overlap)"

# ─────────────────────────────────────────────
# 6. LOAD WORKBOOK & PROCESS ALL PARTICIPANT SHEETS
# ─────────────────────────────────────────────

def clean_stimulus(raw):
    """Strip the syllable count parenthetical from stimulus string."""
    if not isinstance(raw, str):
        return str(raw) if raw is not None else ""
    return re.sub(r'\s*\(\d+\)\s*$', '', raw.strip())


def process_workbook(input_path, output_path):
    wb = openpyxl.load_workbook(input_path)

    # Identify participant sheets (contain '_v')
    participant_sheets = [s for s in wb.sheetnames if '_v' in s]

    all_results = []   # for aggregate stats

    for sheet_name in participant_sheets:
        ws = wb[sheet_name]

        # Find column positions from header row
        header = [cell.value for cell in ws[1]]
        try:
            stim_col   = header.index('Stimulus') + 1        # 1-indexed
            trans_col  = header.index('Transcription Rater 1') + 1
            score_col  = header.index('Score Rater 1') + 1
        except ValueError:
            continue  # skip if header not found

        # Add new columns for auto score and rationale
        auto_score_col    = ws.max_column + 1
        auto_rationale_col = auto_score_col + 1

        # Write headers for new columns
        ws.cell(row=1, column=auto_score_col).value    = 'Auto Score'
        ws.cell(row=1, column=auto_rationale_col).value = 'Auto Rationale'

        human_scores = []
        auto_scores  = []

        for row in ws.iter_rows(min_row=2):
            # Skip empty rows
            if row[0].value is None:
                continue

            stimulus     = clean_stimulus(ws.cell(row=row[0].row, column=stim_col).value)
            transcription = ws.cell(row=row[0].row, column=trans_col).value
            human_score  = ws.cell(row=row[0].row, column=score_col).value

            auto_score, rationale = score_utterance(stimulus, transcription)

            # Write auto score and rationale
            ws.cell(row=row[0].row, column=auto_score_col).value    = auto_score
            ws.cell(row=row[0].row, column=auto_rationale_col).value = rationale

            if isinstance(human_score, (int, float)) and human_score in [0,1,2,3,4]:
                human_scores.append(int(human_score))
                auto_scores.append(auto_score)
                all_results.append({
                    'sheet': sheet_name,
                    'stimulus': stimulus,
                    'transcription': transcription,
                    'human': int(human_score),
                    'auto': auto_score,
                    'rationale': rationale
                })

        # Per-participant stats in a note cell
        if human_scores:
            exact_match = sum(h == a for h, a in zip(human_scores, auto_scores))
            close_match = sum(abs(h - a) <= 1 for h, a in zip(human_scores, auto_scores))
            n = len(human_scores)
            ws.cell(row=ws.max_row + 2, column=1).value = (
                f"Auto-scoring stats: {exact_match}/{n} exact ({exact_match/n:.0%}), "
                f"{close_match}/{n} within ±1 ({close_match/n:.0%})"
            )

    # ── Summary sheet ─────────────────────────
    if 'AutoEIT_Summary' in wb.sheetnames:
        del wb['AutoEIT_Summary']
    summary = wb.create_sheet('AutoEIT_Summary')

    # Aggregate stats
    if all_results:
        n         = len(all_results)
        exact     = sum(r['human'] == r['auto'] for r in all_results)
        within_1  = sum(abs(r['human'] - r['auto']) <= 1 for r in all_results)
        kappa     = cohen_kappa([r['human'] for r in all_results],
                                [r['auto']  for r in all_results],
                                categories=[0,1,2,3,4])

        summary.append(['AutoEIT Test II — Automated Scoring Report'])
        summary.append([''])
        summary.append(['Total sentences scored', n])
        summary.append(['Exact agreement', f"{exact} ({exact/n:.1%})"])
        summary.append(['Within ±1 agreement', f"{within_1} ({within_1/n:.1%})"])
        summary.append(['Weighted Cohen Kappa', f"{kappa:.3f}"])
        summary.append([''])
        summary.append(['Target (project requirement)', '≥ 90% agreement with human raters'])
        summary.append([''])

        # Score distribution comparison
        summary.append(['Score', 'Human count', 'Auto count', 'Human %', 'Auto %'])
        human_dist = Counter(r['human'] for r in all_results)
        auto_dist  = Counter(r['auto']  for r in all_results)
        for s in [0, 1, 2, 3, 4]:
            summary.append([
                s,
                human_dist[s],
                auto_dist[s],
                f"{human_dist[s]/n:.1%}",
                f"{auto_dist[s]/n:.1%}"
            ])

        summary.append([''])
        summary.append(['Disagreement Analysis (|human - auto| > 1)'])
        summary.append(['Sheet', 'Item', 'Stimulus', 'Transcription', 'Human', 'Auto', 'Rationale'])
        for r in all_results:
            if abs(r['human'] - r['auto']) > 1:
                summary.append([
                    r['sheet'],
                    '',
                    r['stimulus'][:60],
                    str(r['transcription'])[:60] if r['transcription'] else '',
                    r['human'],
                    r['auto'],
                    r['rationale']
                ])

        # Print console summary
        print(f"\n{'='*60}")
        print(f"AutoEIT Test II — Scoring Complete")
        print(f"{'='*60}")
        print(f"Sentences scored     : {n}")
        print(f"Exact agreement      : {exact}/{n} = {exact/n:.1%}")
        print(f"Within ±1 agreement  : {within_1}/{n} = {within_1/n:.1%}")
        print(f"Weighted Cohen Kappa : {kappa:.3f}")
        print(f"Output written to    : {output_path}")
        print(f"{'='*60}\n")

    wb.save(output_path)
    return all_results

# ─────────────────────────────────────────────
# 7. WEIGHTED COHEN'S KAPPA (linear weights)
# ─────────────────────────────────────────────

def cohen_kappa(y1, y2, categories):
    """Compute weighted Cohen's Kappa with linear weights."""
    n = len(y1)
    k = len(categories)
    cat_idx = {c: i for i, c in enumerate(categories)}

    # Observed agreement matrix
    obs = [[0]*k for _ in range(k)]
    for a, b in zip(y1, y2):
        if a in cat_idx and b in cat_idx:
            obs[cat_idx[a]][cat_idx[b]] += 1

    # Marginals
    row_sum = [sum(obs[i]) for i in range(k)]
    col_sum = [sum(obs[i][j] for i in range(k)) for j in range(k)]

    # Weighted observed and expected
    w_obs = 0.0
    w_exp = 0.0
    for i in range(k):
        for j in range(k):
            weight = 1 - abs(i - j) / (k - 1)   # linear weight
            w_obs += weight * obs[i][j]
            w_exp += weight * (row_sum[i] * col_sum[j] / n)

    w_obs /= n
    w_exp /= n

    if 1 - w_exp == 0:
        return 1.0
    return (w_obs - w_exp) / (1 - w_exp)

# ─────────────────────────────────────────────
# 8. MAIN
# ─────────────────────────────────────────────

if __name__ == '__main__':
    INPUT  = '/home/renu/Downloads/autoeit-gsoc-2026/Example_EIT Transcription and Scoring Sheet.xlsx'
    OUTPUT = '/home/renu/Downloads/autoeit-gsoc-2026/AutoEIT_Scored_Output.xlsx'

    print("Loading workbook and scoring transcriptions...")
    results = process_workbook(INPUT, OUTPUT)
